### ISSUE TITLE
Question(s): What exactly does goofiboot provide that systemd-boot doesn't anymore.

### ISSUE THREAD

**Issue by FSMaxB** [solus-project/goofiboot#2]
In the README you state that gummiboot supported some features that systemd-boot doesn't support anymore. Could you please specify in the README what those are.

Have you been in contact with the systemd people about this? If yes, what did they say?

Also: Does clr-boot-manager rely on those features?

**Comment by ikeydoherty** [comment]
So the features I put into goofiboot that I cared about, i.e. distro integration, respect of the EFI System Partition, handling edge cases of case sensitivity vs case ignorance, update mechanics, etc, these are all handled now by clr-boot-manager.

The idea is to now drop this fork and rebase Solus onto systemd-boot, and have CBM worry about the distro/update side. Thus things I wanted in `bootctl`, no longer need to be in there, as CBM doesn't use it.

In CBM terms there is a "systemd-class" bootloader, with gummiboot, goofiboot, and sd-boot specific subclasses. They only set up the paths used - it's not dependent on goofiboot at all. The UEFI code in CBM is designed for systemd-boot.

**Comment by FSMaxB** [comment]
Good to know that this fork will be dropped. And thanks for your explanation.
