### ISSUE TITLE
Unable to delete a boot record

### ISSUE THREAD

**Issue by Akyshnik** [solus-project/goofiboot#5]
You cannot delete a record in goofiboot menu.

**Comment by ikeydoherty** [comment]
What do you mean you cannot "delete a record"? If you're not gonna provide details I can't do anything for you. "Records" are stored on the ESP at `loader/entries/*.conf`. If you want one gone, remove it from there.

**Comment by ikeydoherty** [comment]
(Re-open if this is not the case im just tryna keep the tracker clean)

**Comment by Akyshnik** [comment]
Inside the goofiboot menu, you can modify the record, but you cannot delete one. To do this you have to go `loader/entries/*.conf`, but it would be nice if you could delete them inside the menu.

**Comment by ikeydoherty** [comment]
You can only modify it in memory, not on disk. Also note that goofiboot is marked defunct, we'll be recommending people just move to systemd-boot where there is active development. Much of the need for goofiboot (safety, management) has now been superseded by clr-boot-manager

**Comment by Akyshnik** [comment]
So you're saying that Solus will change its default bootloader soon?

**Comment by ikeydoherty** [comment]
Yeah we'll be swapping it out after we've upgraded our systemd package in Solus. The initial rationale for this fork was that gummiboot/systemd-boot didn't care about certain safety aspects for the system, or updating the bootloader across renames, treatment of the ESP, etc. Some of the core things within goofiboot, such as the case-ignorance handling for FAT32, was actually made a core part of clr-boot-manager. clr-boot-manager supports all "systemd-class" bootloaders, so we'd just swap one out for the other, and not use any of the associated tooling for the bootloader.

**Comment by Akyshnik** [comment]
Will there be a way to change a bootloader after Solus installation. Or you will be forced to reinstall the whole system in order to do that?

**Comment by ikeydoherty** [comment]
Oh god no reinstalls! This is us :D Basically we'll switch it over in CBM and the new bootloader will take over. We're tempted to wait until secure boot support is baked in to justify the switch tbh.

**Comment by Akyshnik** [comment]
Thank you for that. Also thanks for development insides!

**Comment by ikeydoherty** [comment]
Ah no worries - we like us a bit of transparency :)
